SilvesterSchneider/CRohM

- frontend/src/app/contacts/contacts-add/contacts-add.component.html
- frontend/src/app/contacts/contacts-add/contacts-add.component.scss
- frontend/src/app/contacts/contacts-add/contacts-add.component.spec.ts
- frontend/src/app/contacts/contacts-add/contacts-add.component.ts
- frontend/src/app/contacts/contacts-list/contacts-list.component.html
- frontend/src/app/contacts/contacts-list/contacts-list.component.ts
- frontend/src/app/contacts/contacts-routing.module.ts
- frontend/src/app/contacts/contacts.module.ts
- package-lock.json
WWD2_3 erledigt. Neue contcts-add-Komponenete erzeugt. Kann neue Kontakte in mock-contacts.ts anlegen.
Hab ich jetzt beim branchen, pushen und pullen alles richtig gemacht?
> WWD2_3 done

- TestProjects/PasswordGeneratorTest.cs
- TestProjects/Properties/launchSettings.json
- TestProjects/TestProjects.csproj
- backend/ModelLayer/Helper/Extensions.cs
- backend/ModelLayer/Helper/PasswordGenerator.cs
- backend/ModelLayer/Helper/RandomSecureVersion.cs
- backend/PasswordgeneratorTest.cs
- backend/WebApi.sln
added a password generator which could be used for password generation in dependency on different kind of parameters like min / max length and min amount of small letters, big letters, numerics and special characters
> password generator

- frontend/src/app/contacts/contacts-add/contacts-add.component.html
- frontend/src/app/contacts/contacts-add/contacts-add.component.ts
- frontend/src/app/contacts/contacts.model.ts
- frontend/src/app/contacts/contacts.module.ts
- frontend/src/app/contacts/mock-contacts.ts
wwd3_3 fertig
- Validierung korrektes EMail-Format gem.  Angular Validators.email
- Validierung korrektes Telefonnummer-Format: Beliebige Anzahl an Ziffern, Leerzeichen und Bindestrichen, Muss mit 0 beginnen 
- Dropdown für Länderauswahl
> Wwd3 3 frontend add contact validation

- backend/ModelLayer/CrmContext.cs
- backend/ModelLayer/Migrations/20200328180110_organizaiontLayers.Designer.cs
- backend/ModelLayer/Migrations/20200328180110_organizaiontLayers.cs
- backend/ModelLayer/Models/Organization.cs
- backend/RepositoryLayer/OrganizationRepository.cs
- backend/ServiceLayer/OrganizationService.cs
created a new table for the organizations to be defined.
an organization contains beside the ID, name and description as well an addess objekt and a list with users who could work there as employees
> added organization table into database

- backend/ModelLayer/DataTransferObjects/ContactPossibilitiesDto.cs
- backend/ModelLayer/DataTransferObjects/OrganizationDto.cs
- backend/ModelLayer/Migrations/20200330185140_added_contact_possibilities.Designer.cs
- backend/ModelLayer/Migrations/20200330185140_added_contact_possibilities.cs
- backend/ModelLayer/Models/ContactPossibilities.cs
- backend/ModelLayer/Models/Organization.cs
- backend/RepositoryLayer/OrganizationRepository.cs
- backend/ServiceLayer/MappingProfile.cs
- backend/ServiceLayer/OrganizationService.cs
- backend/ServiceLayer/UserService.cs
- backend/WebApi/Controllers/OrganizationController.cs
- backend/WebApi/Startup.cs
added the contact possibilities model
> Ram added contact possibilities model

- frontend/src/app/app-routing.module.ts
- frontend/src/app/contacts/contacts.service-mock.ts
- frontend/src/app/contacts/mock-contacts.ts
- frontend/src/app/organizations/organizations-add/organizations-add.component.spec.ts
- frontend/src/app/organizations/organizations-list/organizations-list.component.html
- frontend/src/app/organizations/organizations-list/organizations-list.component.spec.ts
- frontend/src/app/organizations/organizations-list/organizations-list.component.ts
- frontend/src/app/organizations/organizations-routing.module.ts
- frontend/src/app/organizations/organizations.module.ts
aktuell läuft das projekt leider nicht. vermutlich wegen den 3 pull requests welche gemergt wurden. habe innerhalb dieses branches ein paar fehler behoben (erforderlich id parameter in einem dto objekt, fehlende imports in einem front end test und umbenennung einer frontend klasse zu ...List). bei mir lokal baut und läuft es zumindest damit wieder...
> make it run

- frontend/src/app/contacts/contacts-list/contacts-list.component.ts
- frontend/src/app/organizations/organizations-list/organizations-list.component.ts
nun passiert das alles automatisch ohne die seite neu laden zu müssen. habe es auch gleich bei der organisationsübersicht gerade gezogen
> US12_ram_die kontaktliste aktualisieren nachdem ein neuer kontakt eingefügt wurde

- backend/ModelLayer/ModelLayer.csproj
- backend/WebApi/WebApi.csproj
- frontend/src/app/login/login.component.html
- frontend/src/app/login/login.component.ts
key listener registriert und zusätzliche helfermethode zum checken aller voraussetzungen definiert
> Nun wird durch Betätigen der enter taste ebenfalls der login ermöglicht

- backend/WebApi/Helper/ApplicationDbInitializer.cs
- frontend/src/app/login/login.component.ts
Nun wird der user nach dem login korrekter weise auf die landing page geleitet und der admin name beinhaltet nun keinen null wert mehr
> fixed the navigation after login to the home component

- backend/WebApi/Startup.cs
- frontend/src/app/contacts/contacts-list/contacts-list.component.html
- frontend/src/app/contacts/contacts-list/contacts-list.component.scss
- frontend/src/app/contacts/contacts-list/contacts-list.component.ts
- frontend/src/app/events/events-list/events-list.component.html
- frontend/src/app/events/events-list/events-list.component.scss
- frontend/src/app/events/events-list/events-list.component.ts
- frontend/src/app/organizations/organizations-list/organizations-list.component.html
- frontend/src/app/organizations/organizations-list/organizations-list.component.scss
- frontend/src/app/organizations/organizations-list/organizations-list.component.ts
Nun befinden sich alle aktionen oben auf der seite zu beginn und zusätzlich steht ein funktionstüchtiges suchfeld zur verfügung mit dem man nach allen spalten suchen kann
> ram_added the search field and applied the filter function to all components

- frontend/src/app/home/home.component.html
- frontend/src/app/home/home.component.ts
nun funktioniert wieder die details ansicht korrekt innerhalb der landing page (wie sie zuvor eigentlich auch schonmal korrekt funktioniert hat)
> ram_fixed the details view within the home tab

- backend/WebApi/Controllers/DataProtectionController.cs
- backend/WebApi/Controllers/TestController.cs
Solved issues due to async statement, where no await was specified
> Fix backend compiler warnings

- backend/RepositoryLayer/ModificationEntryRepository.cs
warum auch immer wurde mal wieder leider die landing page dahingehend korrupiert als das der user name nicht angezeigt wurde bei den veränderungen der objekte.. ist nun wieder gefixt
> BUG_L1: fixed the user name is showing now again in the landing page

- frontend/src/app/events/events-info/events-info.component.html
- frontend/src/app/organizations/organizations-info/organizations-info.component.html
bei den veranstalltungen und organisationen wurden leider die bearbeiter innerhalb der historie nicht angzeigt..das ist nun gefixt
> BUG_L2: der bearbeiter innerhalb der historie wird nun wieder angezeigt

- .github/dependabot.yml
- .github/workflows/CI_Build.yml
- .github/workflows/PR_Build.yml
- .github/workflows/cancel.yml
- .github/workflows/dependabot.yml
Dependabot reviewed und merged sich jetzt selbst, wenn die Builds in Ordnung sind
> Dependabot auto merge and approve

- backend/ModelLayer/Helper/ComparerForModificationEntryCreation.cs
- backend/ModelLayer/Migrations/20201023120857_ramInit_add_mod.Designer.cs
- backend/ModelLayer/Migrations/20201023120857_ramInit_add_mod.cs
- backend/ModelLayer/Migrations/CrmContextModelSnapshot.cs
- backend/ModelLayer/Models/Contact.cs
- backend/ModelLayer/Models/ModificationEntry.cs
Nun wird auch die Veränderung des Geschlechts bzw. des Ansprechpartners beim Kontakt korrekterweise im Datenveränderungsprotokoll vermerkt
> ram_added_modification_entries

- frontend/src/app/events/events-info/events-info.component.html
- frontend/src/app/events/events-info/events-info.component.ts
nun werden auch bei den infos der veranstaltung alle datenveränderungen in pagination dargestellt
> added pagination in events info

- backend/RepositoryLayer/EventRepository.cs
- backend/ServiceLayer/StatisticsService.cs
- frontend/src/app/events/events-detail/events-detail.component.ts
- frontend/src/app/settings/roles/update-role/update-role.component.html
- frontend/src/app/shared/charts/vertical-grouped-bar-chart/vertical-grouped-bar-chart.component.ts
- frontend/src/app/statistics/tags/tags.component.html
Nun werden auch die Organisationen korrekterweise bei den Veranstaltungsteilnehmern berücksichtigt. Die daten filterung bei statistiken generell funktioniert nun auch einwandfrei. Text neu positioniert
> ram fixed statistics things

- frontend/src/app/contacts/contacts-list/contacts-list.component.html
Nun kann man an jede person direkt eine mail senden..den anderen fehler gab es erst garnicht den er angemeckert hatte
> ram_bug4_opt_contacts

- backend/ServiceLayer/MailService.cs
- backend/WebApi/Controllers/ContactController.cs
Nun werden alle mail funktionen auch asynchron ausgeführt -> wesentlich schnellere bearbeitung...
> ram_improved mail service

- backend/ServiceLayer/MailService.cs
- backend/Tests/UnitTests/ServiceLayer/MailServiceTests.cs
- frontend/src/app/settings/mail/mail.component.ts
Nun sollten wieder die settings genutzt werden, welche man über das front end speichert
> ram_fixed_mail_settings

- frontend/src/app/contacts/contacts-list/contacts-list.component.html
- frontend/src/app/contacts/contacts-list/contacts-list.component.ts
- frontend/src/assets/i18n/de.json
- frontend/src/assets/i18n/en.json
Nun steht die PLZ neben dem ort bei der kontaktübersicht zur verfügung und zusätzlich heißt es nun überall Stadt und nicht mehr Ort
> ram_bug_3_opt

- frontend/src/app/contacts/contacts-list/contacts-list.component.html
- frontend/src/app/contacts/contacts-list/contacts-list.component.scss
- frontend/src/app/contacts/contacts-list/contacts-list.component.ts
- frontend/src/app/organizations/organizations-list/organizations-list.component.html
- frontend/src/app/organizations/organizations-list/organizations-list.component.scss
- frontend/src/app/organizations/organizations-list/organizations-list.component.ts
- frontend/src/app/shared/charts/vertical-grouped-bar-chart/vertical-grouped-bar-chart.component.ts
entsprechend dem wireframe für bugfix_cus2 die globale checkbox ausgerichtet und den mouseleave event registriert
> ram_bugfix_cus2

- frontend/src/app/contacts/contacts-list/contacts-list.component.html
- frontend/src/app/contacts/contacts-list/contacts-list.component.ts
- frontend/src/app/shared/tags-filter/tags-filter.component.html
- frontend/src/app/shared/tags-filter/tags-filter.component.scss
Hi Michelle,
ich hab hier noch das CSS Problem was ich dir geschrieben hab. 
Kannst du mir da weiterhelfen?
Die HTML Datei heißt:
tags-filter.component.html
> Optimierungen nach Markus OPT_1

- frontend/src/app/home/home.component.html
Nun stehen die korrekten infos dran bei den veranstaltungen auf der landing page
> ram_fix_landing_page

- misc/docker-compose-up.sh
> changed docker-compuse-up.sh file

- frontend/src/app/events/events-add/events-add.component.html
- frontend/src/app/events/events-add/events-add.component.scss
- frontend/src/app/events/events-detail/events-detail.component.html
- frontend/src/app/events/events-detail/events-detail.component.scss
- frontend/src/app/events/events-list/events-list.component.ts
veranstaltungen: feld datum hat nun die selbe länge wie die anderen felder, anpassung der ausrichtung der tabelle der stati
> ram_bug14_17

- frontend/src/app/contacts/contacts-list/contacts-list.component.html
- frontend/src/app/contacts/contacts-list/contacts-list.component.scss
- frontend/src/app/events/events-add/events-add.component.html
- frontend/src/app/events/events-add/events-add.component.scss
- frontend/src/app/events/events-detail/events-detail.component.html
- frontend/src/app/events/events-detail/events-detail.component.scss
- frontend/src/app/events/events-list/events-list.component.html
- frontend/src/app/home/home.component.html
- frontend/src/app/home/home.component.scss
- frontend/src/app/organizations/organizations-list/organizations-list.component.html
- frontend/src/app/organizations/organizations-list/organizations-list.component.scss
auf wunsch von markus hier noch ein paar fixes:
landing page: farbe auf primary geändert und button mittig mit weng rand positioniert
event list: die ganze zeile der heutigen veranstaltung wird nun komplett eingefärbt
kontakt / organisationsliste: nun ist der verfluchte scheiss drecksrahmen bei dem menü endlich weg :)
> ram_bugfix_markus_telegram

- frontend/src/app/calendar/calendar.component.html
- frontend/src/app/calendar/calendar.component.scss
- frontend/src/app/calendar/calendar.component.ts
- frontend/src/assets/i18n/de.json
- frontend/src/assets/i18n/en.json
Nun gibt es die möglichkeit auch die jahre bequem zu wechseln innerhalb der kalenderübersicht
> ram_cal_extended

- backend/WebApi/Controllers/UsersController.cs
- frontend/src/app/settings/user/add-user/add-user.component.ts
- frontend/src/app/shared/api-generated/api-generated.ts
nun wird eine korrekte fehlermedlung angezeigt wenn man einen user versucht anzulegen, dessen mail bereits vergeben ist
> ram_bugfix_user_error

- frontend/src/app/organizations/organizations-edit-dialog/organizations-edit-dialog.component.html
- frontend/src/app/organizations/organizations-edit-dialog/organizations-edit-dialog.component.scss
Nun sind die felder der Mitarbeiterauswahl und der Tags auf selber höhe wie die anderen sachen. zusätzlich noch eine überschrift für die mitarbeiter eingefügt
> ram_bugfix_org_dialog

- frontend/src/app/events/events-add/events-add.component.html
- frontend/src/app/events/events-add/events-add.component.ts
- frontend/src/app/home/home.component.ts
- frontend/src/app/shared/data-protection/dp-disclaimer-dialog/dp-disclaimer-dialog.component.html
- frontend/src/app/shared/data-protection/dp-disclaimer-dialog/dp-disclaimer-dialog.component.ts
- frontend/src/assets/i18n/de.json
- frontend/src/assets/i18n/en.json
angepasster dialog für benutzer die keine rollen verteilen dürfen wenn kein datenschutzbeauftragter vorhanden ist
> ram_fixed_data_protection_officer_missing_message

- backend/WebApi/Startup.cs
- frontend/src/app/events/events-detail/events-detail.component.html
- frontend/src/app/events/events-detail/events-detail.component.scss
Nun sind die felder weng fetter und zentrisch angeordnet innerhalb des bearbeitungsdialogs von den veranstaltungen
> ram_bugfix_kal_dialog2

- backend/ModelLayer/DataTransferObjects/ContactDto.cs
- backend/ModelLayer/DataTransferObjects/UserDto.cs
- backend/RepositoryLayer/ContactRepository.cs
- backend/ServiceLayer/MailService.cs
- backend/WebApi/Controllers/ContactController.cs
- frontend/src/app/contacts/contacts-list/contacts-list.component.html
- frontend/src/app/contacts/contacts-list/contacts-list.component.scss
- frontend/src/app/home/home.component.html
- frontend/src/app/home/home.component.ts
- frontend/src/app/organizations/organizations-list/organizations-list.component.ts
- frontend/src/app/shared/api-generated/api-generated.ts
- frontend/src/app/shared/jwt.service.ts
- frontend/src/assets/i18n/de.json
- frontend/src/assets/i18n/en.json
Entsprechend einem screenshot vom markus ein paar sachen angepasst + die möglichkeit bereitgestellt das wenn man als superadmin eingeloggt ist, auch immer auch alle unbestätigten kontakte sehen kann...
> ram_fixed_some_general_issues

- backend/ServiceLayer/MailService.cs
nun steht ein anderer text in der approve mail drin + <br geschlossen bei registratur mail
> ram_fixed mail content

- backend/RepositoryLayer/ModificationEntryRepository.cs
- backend/ServiceLayer/UserCheckDateService.cs
- backend/ServiceLayer/UserService.cs
- backend/WebApi/Controllers/UsersController.cs
- frontend/src/app/settings/user/user.component.html
- frontend/src/app/settings/user/user.component.ts
- frontend/src/app/shared/api-generated/api-generated.ts
- frontend/src/assets/i18n/de.json
- frontend/src/assets/i18n/en.json
Nun kann auch ein benutzer im nachgang wieder aus dem system gänzlich gelöscht werden...
> ram_user_deletion

- frontend/src/app/approve-contact/approve-contact.component.html
Markus wolle die Landingpage vom Contact Approven noch auf Englisch haben.
> Approve Contact in Englisch

- frontend/src/app/settings/user/user.component.html
die icons in der user übersicht angepasst und auch die reihenfolge davon
> ram_BUGFIX_MARKUS_TELEGRAM_2

- backend/WebApi/Startup.cs
- frontend/src/app/settings/user/user.component.html
- frontend/src/app/settings/user/user.component.ts
nun kann tatsächlich nur der superadmin seinen eigenen user bearbeiten und das password zurücksetzen
> ram_fixed_locking_state

- frontend/src/app/contacts/contacts-info/contacts-info.component.ts
- frontend/src/app/events/events-info/events-info.component.ts
- frontend/src/app/organizations/organizations-info/organizations-info.component.ts
nun wird nachdem aus dem info dialog der bearbeitungsdialog geöffnet wird, nachdem dieser wieder geschlossen wird, der zuvor geölffnete info dialog aktualisiert
> ram_actualizing_dialog

- frontend/src/app/contacts/contacts-edit-dialog/contacts-edit-dialog.component.html
- frontend/src/app/contacts/contacts-edit-dialog/contacts-edit-dialog.component.scss
- frontend/src/app/contacts/contacts-list/contacts-list.component.html
- frontend/src/app/contacts/contacts-list/contacts-list.component.scss
- frontend/src/app/events/events-detail/events-detail.component.html
- frontend/src/app/events/events-detail/events-detail.component.scss
- frontend/src/app/events/events-list/events-list.component.html
- frontend/src/app/events/events-list/events-list.component.scss
- frontend/src/app/login/login.component.html
- frontend/src/app/login/login.component.scss
- frontend/src/app/login/login.component.ts
- frontend/src/app/organizations/organizations-edit-dialog/organizations-edit-dialog.component.html
- frontend/src/app/organizations/organizations-edit-dialog/organizations-edit-dialog.component.scss
- frontend/src/app/organizations/organizations-list/organizations-list.component.html
- frontend/src/app/organizations/organizations-list/organizations-list.component.scss
- frontend/src/app/settings/roles/roles.component.ts
- frontend/src/app/shared/jwt.service.ts
- frontend/src/app/shared/tags-filter/tags-filter.component.html
- frontend/src/app/shared/tags-filter/tags-filter.component.scss
- frontend/src/styles.scss
- tests/integration/03_settings/roles_spec.ts
- tests/integration/05_contacts/contacts_spec.ts
- tests/integration/06_organizations/organizations_spec.ts
- tests/integration/07_events/events_spec.ts
- tests/shared/login.ts
1) Tags im Bearbeiten-Dialog haben einen viereckigen Rahmen um den Schließen-Button, diesen bitte entfernen
2) Jetzt, wo ihr wisst, wie man Elemente innerhalb eines Eingabefeldes positionieren kann, könntet ihr bitte noch das Augen-Symbol vom Passwort in dessen Eingabe rechts-zentriert anzeigen lassen *g* ;)
3) Die Dummydaten hinzufügen etwas breiter (sind nun abgeschnitten)
> BUG18_2: unify tags styling; fix viewPassword icon; fix and unify dummy button

- frontend/src/app/contacts/contacts-list/contacts-list.component.ts
nun wird der ansprechpartner beim filtern der datensätze bei der kontaktübersicht berücksichtigt
> ram_added contact partner filter

- README.md
- backend/RepositoryLayer/EventRepository.cs
- backend/WebApi/Controllers/AuthController.cs
- backend/WebApi/Controllers/ContactController.cs
- backend/WebApi/Controllers/EventController.cs
- backend/WebApi/Controllers/OrganizationController.cs
- backend/WebApi/Controllers/RoleController.cs
- frontend/src/app/shared/osm/osm-address/osm-address.component.ts
- tests/integration/02_login/login_spec.ts
- tests/integration/03_settings/roles_spec.ts
- tests/integration/04_home/home_spec.ts
- tests/integration/05_contacts/contacts_spec.ts
- tests/integration/06_organizations/organizations_spec.ts
- tests/integration/07_events/events_spec.ts
Die erforderlichen Einzelberechtigungen zum Nutzen der Controller Funktionen geupdatet. alle UND bedingungen entfernt
> ram_updated claims
